/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *Backspace;
  GtkWidget *CE;
  GtkWidget *Clr;
  GtkWidget *Division;
  GtkWidget *Seven;
  GtkWidget *Eight;
  GtkWidget *Nine;
  GtkWidget *Multiplication;
  GtkWidget *Four;
  GtkWidget *Five;
  GtkWidget *Six;
  GtkWidget *Substraction;
  GtkWidget *One;
  GtkWidget *Two;
  GtkWidget *Three;
  GtkWidget *Addition;
  GtkWidget *Modulous;
  GtkWidget *Zero;
  GtkWidget *Decimal;
  GtkWidget *Equals;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 136, 32);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  Backspace = gtk_button_new_with_mnemonic (_("Bksp"));
  gtk_widget_show (Backspace);
  gtk_fixed_put (GTK_FIXED (fixed1), Backspace, 24, 88);
  gtk_widget_set_size_request (Backspace, 70, 29);

  CE = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (CE);
  gtk_fixed_put (GTK_FIXED (fixed1), CE, 128, 88);
  gtk_widget_set_size_request (CE, 69, 29);

  Clr = gtk_button_new_with_mnemonic (_("Clr"));
  gtk_widget_show (Clr);
  gtk_fixed_put (GTK_FIXED (fixed1), Clr, 232, 88);
  gtk_widget_set_size_request (Clr, 70, 29);

  Division = gtk_button_new_with_mnemonic (_("/"));
  gtk_widget_show (Division);
  gtk_fixed_put (GTK_FIXED (fixed1), Division, 336, 88);
  gtk_widget_set_size_request (Division, 69, 29);

  Seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (Seven);
  gtk_fixed_put (GTK_FIXED (fixed1), Seven, 24, 136);
  gtk_widget_set_size_request (Seven, 70, 29);

  Eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (Eight);
  gtk_fixed_put (GTK_FIXED (fixed1), Eight, 128, 136);
  gtk_widget_set_size_request (Eight, 70, 29);

  Nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (Nine);
  gtk_fixed_put (GTK_FIXED (fixed1), Nine, 232, 136);
  gtk_widget_set_size_request (Nine, 70, 29);

  Multiplication = gtk_button_new_with_mnemonic (_("*"));
  gtk_widget_show (Multiplication);
  gtk_fixed_put (GTK_FIXED (fixed1), Multiplication, 336, 136);
  gtk_widget_set_size_request (Multiplication, 69, 29);

  Four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (Four);
  gtk_fixed_put (GTK_FIXED (fixed1), Four, 24, 184);
  gtk_widget_set_size_request (Four, 70, 29);

  Five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (Five);
  gtk_fixed_put (GTK_FIXED (fixed1), Five, 128, 184);
  gtk_widget_set_size_request (Five, 79, 29);

  Six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (Six);
  gtk_fixed_put (GTK_FIXED (fixed1), Six, 232, 184);
  gtk_widget_set_size_request (Six, 79, 29);

  Substraction = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (Substraction);
  gtk_fixed_put (GTK_FIXED (fixed1), Substraction, 336, 184);
  gtk_widget_set_size_request (Substraction, 78, 29);

  One = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (One);
  gtk_fixed_put (GTK_FIXED (fixed1), One, 24, 232);
  gtk_widget_set_size_request (One, 79, 29);

  Two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (Two);
  gtk_fixed_put (GTK_FIXED (fixed1), Two, 128, 232);
  gtk_widget_set_size_request (Two, 78, 29);

  Three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (Three);
  gtk_fixed_put (GTK_FIXED (fixed1), Three, 232, 232);
  gtk_widget_set_size_request (Three, 79, 29);

  Addition = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (Addition);
  gtk_fixed_put (GTK_FIXED (fixed1), Addition, 336, 232);
  gtk_widget_set_size_request (Addition, 79, 29);

  Modulous = gtk_button_new_with_mnemonic (_("%"));
  gtk_widget_show (Modulous);
  gtk_fixed_put (GTK_FIXED (fixed1), Modulous, 24, 280);
  gtk_widget_set_size_request (Modulous, 79, 29);

  Zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (Zero);
  gtk_fixed_put (GTK_FIXED (fixed1), Zero, 128, 280);
  gtk_widget_set_size_request (Zero, 78, 29);

  Decimal = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (Decimal);
  gtk_fixed_put (GTK_FIXED (fixed1), Decimal, 232, 280);
  gtk_widget_set_size_request (Decimal, 79, 29);

  Equals = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (Equals);
  gtk_fixed_put (GTK_FIXED (fixed1), Equals, 336, 280);
  gtk_widget_set_size_request (Equals, 78, 29);

  g_signal_connect ((gpointer) Backspace, "clicked",
                    G_CALLBACK (on_Backspace_clicked),
                    NULL);
  g_signal_connect ((gpointer) CE, "clicked",
                    G_CALLBACK (on_CE_clicked),
                    NULL);
  g_signal_connect ((gpointer) Clr, "clicked",
                    G_CALLBACK (on_Clr_clicked),
                    NULL);
  g_signal_connect ((gpointer) Division, "clicked",
                    G_CALLBACK (on_Division_clicked),
                    NULL);
  g_signal_connect ((gpointer) Seven, "clicked",
                    G_CALLBACK (on_Seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) Eight, "clicked",
                    G_CALLBACK (on_Eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) Nine, "clicked",
                    G_CALLBACK (on_Nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) Multiplication, "clicked",
                    G_CALLBACK (on_Multiplication_clicked),
                    NULL);
  g_signal_connect ((gpointer) Five, "clicked",
                    G_CALLBACK (on_Five_clicked),
                    NULL);
  g_signal_connect ((gpointer) Six, "clicked",
                    G_CALLBACK (on_Six_clicked),
                    NULL);
  g_signal_connect ((gpointer) Substraction, "clicked",
                    G_CALLBACK (on_Substraction_clicked),
                    NULL);
  g_signal_connect ((gpointer) One, "clicked",
                    G_CALLBACK (on_One_clicked),
                    NULL);
  g_signal_connect ((gpointer) Two, "clicked",
                    G_CALLBACK (on_Two_clicked),
                    NULL);
  g_signal_connect ((gpointer) Three, "clicked",
                    G_CALLBACK (on_Three_clicked),
                    NULL);
  g_signal_connect ((gpointer) Addition, "clicked",
                    G_CALLBACK (on_Addition_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modulous, "clicked",
                    G_CALLBACK (on_Modulous_clicked),
                    NULL);
  g_signal_connect ((gpointer) Zero, "clicked",
                    G_CALLBACK (on_Zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) Decimal, "clicked",
                    G_CALLBACK (on_Decimal_clicked),
                    NULL);
  g_signal_connect ((gpointer) Equals, "clicked",
                    G_CALLBACK (on_Equals_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, Backspace, "Backspace");
  GLADE_HOOKUP_OBJECT (window1, CE, "CE");
  GLADE_HOOKUP_OBJECT (window1, Clr, "Clr");
  GLADE_HOOKUP_OBJECT (window1, Division, "Division");
  GLADE_HOOKUP_OBJECT (window1, Seven, "Seven");
  GLADE_HOOKUP_OBJECT (window1, Eight, "Eight");
  GLADE_HOOKUP_OBJECT (window1, Nine, "Nine");
  GLADE_HOOKUP_OBJECT (window1, Multiplication, "Multiplication");
  GLADE_HOOKUP_OBJECT (window1, Four, "Four");
  GLADE_HOOKUP_OBJECT (window1, Five, "Five");
  GLADE_HOOKUP_OBJECT (window1, Six, "Six");
  GLADE_HOOKUP_OBJECT (window1, Substraction, "Substraction");
  GLADE_HOOKUP_OBJECT (window1, One, "One");
  GLADE_HOOKUP_OBJECT (window1, Two, "Two");
  GLADE_HOOKUP_OBJECT (window1, Three, "Three");
  GLADE_HOOKUP_OBJECT (window1, Addition, "Addition");
  GLADE_HOOKUP_OBJECT (window1, Modulous, "Modulous");
  GLADE_HOOKUP_OBJECT (window1, Zero, "Zero");
  GLADE_HOOKUP_OBJECT (window1, Decimal, "Decimal");
  GLADE_HOOKUP_OBJECT (window1, Equals, "Equals");

  return window1;
}

